// rba | fit - Program Data

const PS = new Date(2026, 3, 6);
const DO = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"];
const DL = { monday: "Mon", tuesday: "Tue", wednesday: "Wed", thursday: "Thu", friday: "Fri", saturday: "Sat", sunday: "Sun" };
const IC = { REST: "#444", EASY: "#4ade80", "EASY-MOD": "#86efac", MODERATE: "#d4a43a", "MOD-HARD": "#fb923c", HARD: "#f87171" };

const P0 = {
    monday: { t: "Full Body Strength A", i: "MODERATE", d: "45 min", ic: "🏋️", b: [{ n: "Warm-Up — 10 min", it: ["Hip Openers", "Thoracic Rotations", "World's Greatest Stretch", "Leg Swings", "Band Pull-Aparts"] }, { n: "Main Work", it: ["Goblet Squat — 3×12", "DB Floor Press — 3×12", "Single-Arm DB Row — 3×10 each", "KB Romanian Deadlift — 3×12", "Half-Kneeling DB Shoulder Press — 3×10 each"] }, { n: "Core", it: ["Dead Bug — 3×10 each side", "Front Plank — 2×30s"] }, { n: "Cool-Down", it: ["Hip Flexor Stretch", "Hamstring Stretch", "Chest Opener", "Lat Stretch"] }] },
    tuesday: { t: "Recovery · Mobility", i: "EASY", d: "30-35 min", ic: "🧘", rc: true, op: ["Light jog (15 min zone 2) + mobility", "Yoga flow (30 min)", "Walk (20 min) + deep stretch", "Bike ride (20 min easy) + stretch"], b: [{ n: "Mobility — 20 min", it: ["Pigeon — 60s each", "Couch Stretch — 60s each", "Thoracic Spine Rotation — 60s each", "Seated Hamstring Stretch — 60s each", "Doorway Chest Stretch — 60s each", "Cat-Cow — 10 reps", "Child's Pose — 60s"] }] },
    wednesday: { t: "Full Body Strength B", i: "MODERATE", d: "45 min", ic: "🏋️", b: [{ n: "Warm-Up — 10 min", it: ["Hip Openers", "Thoracic Rotations", "World's Greatest Stretch", "Leg Swings", "Band Pull-Aparts"] }, { n: "Main Work", it: ["DB Reverse Lunge — 3×10 each", "Push-Up (3s negative) — 3×10", "KB Swing — 3×15", "DB Bent-Over Row — 3×12", "Slider Body Saw — 3×8"] }, { n: "Core", it: ["Bird Dog — 3×8 each", "Side Plank — 2×20s each"] }, { n: "Cool-Down", it: ["Hip Flexors", "Hamstrings", "Chest", "Thoracic Spine"] }] },
    thursday: { t: "Footwork + Mobility", i: "EASY", d: "30 min", ic: "👟", b: [{ n: "Ladder Drills — learning pace", it: ["Icky Shuffle — 2 rounds", "In-Out — 2 rounds", "Lateral Shuffle — 2 rounds", "Carioca — 2 rounds"] }, { n: "Movement", it: ["Lateral Bounds (low intensity) — 2×8 each", "A-Skip — 2×30 yds", "B-Skip — 2×30 yds", "High Knees — 2×30 yds", "Butt Kicks — 2×30 yds"] }, { n: "Deep Stretch — 10 min", it: ["90/90 Hips — 90s each", "Pigeon — 90s each", "Thoracic Rotation — 60s each", "Hamstring Stretch — 60s each"] }] },
    friday: { t: "Full Body Strength C", i: "MODERATE", d: "45 min", ic: "🏋️", b: [{ n: "Warm-Up — 10 min", it: ["Hip Openers", "Thoracic Rotations", "World's Greatest Stretch", "Leg Swings", "Band Pull-Aparts"] }, { n: "Main Work", it: ["DB Sumo Squat — 3×12", "Incline Push-Up to DB Row — 3×8 each", "Single-Leg RDL (light DB) — 3×8 each", "DB Lateral Raise — 3×12", "Exercise Ball Hamstring Curl — 3×10"] }, { n: "Core", it: ["Pallof Press (band) — 3×8 each", "Plank Shoulder Tap — 2×10 each"] }, { n: "Cool-Down", it: ["Hip Flexors", "Hamstrings", "Chest", "Lats"] }] },
    saturday: { t: "Track: Easy Run + Strides", i: "EASY-MOD", d: "35 min", ic: "🏟️", eq: "Jump rope, water", b: [{ n: "Run", it: ["Easy jog — 10 min"] }, { n: "Strides + Movement", it: ["80m Strides at 60-70% — 4 reps (walk back)", "Lateral Shuffle — 20 yds each direction × 4"] }, { n: "Stretch — 10 min", it: ["Hip Flexors — 90s each", "Hamstrings — 90s each", "Quads — 60s each", "Thoracic Bridge — 60s each", "Calf Stretch — 60s each"] }] },
    sunday: { t: "Recovery · Rest", i: "REST", d: "20-30 min", ic: "😴", rc: true, op: ["Full rest", "Easy walk (20 min)", "Gentle yoga / stretch (20 min)", "Foam rolling + breathing"], b: [{ n: "", it: ["Choose one recovery option above. Prioritize sleep tonight."] }] },
};

const P1A = {
    monday: { t: "Lower Strength A", i: "HARD", d: "60 min", ic: "🦵", b: [{ n: "Warm-Up — 8 min", it: ["Hip Openers", "World's Greatest Stretch", "Leg Swings", "Glute Bridges"] }, { n: "Main Work", it: ["DB Bulgarian Split Squat — 4×10 each", "KB Sumo Deadlift — 4×10", "Superset: Slider Reverse Lunge / Ex. Ball Ham Curl — 3×10 each", "Single-Leg Calf Raise (weighted) — 3×15 each", "KB Goblet Lateral Lunge — 3×8 each"] }, { n: "Core", it: ["Hollow Body Hold — 30s", "Bicycle Crunch — 20 reps", "Slider Plank to Pike — 8 reps", "→ 2 rounds"] }] },
    tuesday: { t: "Upper Push/Pull A", i: "HARD", d: "60 min", ic: "💪", b: [{ n: "Warm-Up — 8 min", it: ["Hip Openers", "Thoracic Rotations", "Arm Circles", "Band Pull-Aparts"] }, { n: "Main Work", it: ["DB Floor Press — 4×10", "DB Bent-Over Row — 4×10", "Superset: DB Incline Push-Up Press / Face Pull (band) — 3×12", "Superset: DB Shoulder Press / Single-Arm Row — 3×10", "Superset: DB Curl / Overhead Tricep Extension — 3×12", "Rear Delt Flye — 3×15"] }, { n: "Core", it: ["Exercise Ball Rollout — 3×10", "Pallof Press — 3×8 each"] }] },
    wednesday: { t: "Conditioning A + Core", i: "MODERATE", d: "55 min", ic: "🔥", b: [{ n: "Warm-Up — 8 min", it: ["Hip Openers", "Leg Swings", "Ladder: Icky Shuffle", "Ladder: In-Out"] }, { n: "Circuit — 45s/25s, 75% effort", it: ["Round 1 (×3): Jump Rope → KB Swing → Push-Up → Slider Mt. Climber → Squat", "Round 2 (×3): Lateral Shuffle → Plank-to-Push-Up → DB Thruster → Skater Bounds → Ex. Ball Pass"] }, { n: "Core — 10 min", it: ["V-Ups — 12", "Side Plank Dips — 10 each", "Ex. Ball Knee Tuck — 12", "Dead Bug w/ Weight — 10 each", "→ 2 rounds"] }] },
    thursday: { t: "Footwork + Agility A", i: "EASY-MOD", d: "35 min", ic: "👟", b: [{ n: "Ladder Drills", it: ["Ali Shuffle — 3 rounds", "Crossover — 3 rounds", "5-Hop-and-Stick — 3 rounds"] }, { n: "Agility", it: ["5-10-5 Shuttle at 70% — 4 reps", "Lateral Bound to Stick — 3×6 each", "Carioca w/ Hip Turn — 3×30 yds", "Backpedal to Sprint at 70% — 4×20 yds"] }, { n: "Mobility — 10 min", it: ["90/90 Hips", "Couch Stretch", "Thoracic Foam Roll", "Banded Hip Distraction"] }] },
    friday: { t: "Full Body Power A", i: "HARD", d: "60 min", ic: "⚡", b: [{ n: "Warm-Up — 8 min", it: ["Hip Openers", "Thoracic Rotations", "World's Greatest Stretch", "Leg Swings"] }, { n: "Main Work", it: ["KB Clean and Press — 4×6 each", "DB Jump Squat (light) — 4×8", "Superset: Push-Up w/ Rotation / DB Row — 3×10 each", "Med Ball Slam — 3×10", "Farmer's Carry — 3×40 yds", "Superset: DB Lateral Raise / Band Pull-Apart — 3×12"] }, { n: "Core", it: ["Plank Pull-Through (DB) — 3×8 each", "Exercise Ball Pike — 3×8"] }] },
    saturday: { t: "Track Day A", i: "MOD-HARD", d: "55 min", ic: "🏟️", eq: "Jump rope, sliders, water", b: [{ n: "Warm-Up — 10 min", it: ["Easy Jog", "Hip Openers", "Leg Swings", "A-Skips", "B-Skips", "High Knees"] }, { n: "Agility — 10 min", it: ["Ladder Drills at 80%", "T-Drill — 3 reps", "5-10-5 Shuttle — 4 reps"] }, { n: "Conditioning — 15 min", it: ["200m Repeats at 75% — 3 reps (walk back)", "100m at 80% — 2 reps"] }, { n: "Core — 10 min", it: ["Sprinter Sit-Ups — 12 each", "Plank Walkout — 8", "Mountain Climber — 20", "V-Up — 12", "Superman Hold — 30s", "→ 2 rounds"] }, { n: "Cool-Down", it: ["Jog + stretch"] }] },
    sunday: { t: "Recovery · Rest", i: "REST", d: "20-30 min", ic: "😴", rc: true, op: ["Full rest", "Easy walk (20 min)", "Gentle yoga / stretch", "Foam rolling + breathing"], b: [{ n: "", it: ["Choose one recovery option above."] }] },
};

const P1B = {
    monday: { t: "Lower Strength B", i: "HARD", d: "60 min", ic: "🦵", b: [{ n: "Warm-Up — 8 min", it: ["Hip Openers", "World's Greatest Stretch", "Leg Swings", "Glute Bridges"] }, { n: "Main Work", it: ["DB Front Squat — 4×10", "Single-Leg RDL (DB) — 4×8 each", "Superset: DB Step-Up / Slider Hamstring Curl — 3×10 each", "KB Swing — 4×12", "DB Goblet Curtsy Lunge — 3×8 each"] }, { n: "Core", it: ["Dead Bug w/ Weight — 10 each", "Side Plank — 30s each", "Ex. Ball Pass — 12 reps", "→ 2 rounds"] }] },
    tuesday: { t: "Upper Push/Pull B", i: "HARD", d: "60 min", ic: "💪", b: [{ n: "Warm-Up — 8 min", it: ["Hip Openers", "Thoracic Rotations", "Arm Circles", "Band Pull-Aparts"] }, { n: "Main Work", it: ["DB Incline Press (floor, elevated hips) — 4×10", "Single-Arm DB Row (knee on bench) — 4×10 each", "Superset: Diamond Push-Up / Band Face Pull — 3×12", "Superset: Arnold Press / Chest-Supported Row — 3×10", "Superset: Hammer Curl / Tricep Dip (bench) — 3×12", "Band Pull-Apart — 3×20"] }, { n: "Core", it: ["Plank Shoulder Tap — 3×10 each", "Russian Twist — 3×20"] }] },
    wednesday: { t: "Conditioning B + Core", i: "MODERATE", d: "55 min", ic: "🔥", b: [{ n: "Warm-Up — 8 min", it: ["Hip Openers", "Leg Swings", "Ladder: Icky Shuffle", "Ladder: In-Out"] }, { n: "Circuit — 45s/25s, 75% effort", it: ["Round 1 (×3): High Knees → DB Snatch → Slider Push-Up → Squat Jump → Band Pull-Apart", "Round 2 (×3): Carioca → Burpee (controlled) → KB Swing → Slider Mt. Climber → Plank Hold"] }, { n: "Core — 10 min", it: ["Hollow Body Hold — 30s", "Bicycle Crunch — 20", "Plank Drag (DB) — 8 each", "Ex. Ball Rollout — 10", "→ 2 rounds"] }] },
    thursday: { t: "Footwork + Agility B", i: "EASY-MOD", d: "35 min", ic: "👟", b: [{ n: "Ladder Drills", it: ["Lateral Icky — 3 rounds", "In-Out-In — 3 rounds", "Single-Leg Hop — 3 rounds each"] }, { n: "Agility", it: ["T-Drill at 70% — 4 reps", "Reactive Lateral Shuffle — 3×10 yds each", "A-Skip to Sprint at 70% — 4×20 yds", "Broad Jump to Backpedal — 3×4"] }, { n: "Mobility — 10 min", it: ["Pigeon — 90s each", "Thoracic Rotation — 60s each", "Banded Shoulder Distraction — 60s each", "Calf Stretch — 60s each"] }] },
    friday: { t: "Full Body Power B", i: "HARD", d: "60 min", ic: "⚡", b: [{ n: "Warm-Up — 8 min", it: ["Hip Openers", "Thoracic Rotations", "World's Greatest Stretch", "Leg Swings"] }, { n: "Main Work", it: ["DB Thruster — 4×8", "Broad Jump — 4×5", "Superset: Renegade Row / Explosive Push-Up — 3×8 each", "KB Goblet Squat to Press — 3×10", "Suitcase Carry (single arm) — 3×40 yds each", "Superset: DB Reverse Flye / DB Curl — 3×12"] }, { n: "Core", it: ["Ex. Ball Knee Tuck — 3×10", "Pallof Press — 3×8 each"] }] },
    saturday: { t: "Track Day B", i: "MOD-HARD", d: "55 min", ic: "🏟️", eq: "Jump rope, sliders, water", b: [{ n: "Warm-Up — 10 min", it: ["Easy Jog", "Hip Openers", "Leg Swings", "High Knees"] }, { n: "Agility — 10 min", it: ["Ladder Drills at 80%", "Pro Agility (5-10-5) — 4 reps", "L-Drill — 3 reps"] }, { n: "Conditioning — 15 min", it: ["150m at 80% — 4 reps (walk back)", "50m Sprint at 85% — 3 reps", "400m at 70% — 1 rep"] }, { n: "Core — 10 min", it: ["Bicycle Crunch — 20", "Plank to Push-Up — 10", "Flutter Kicks — 20 each", "Burpee — 6", "V-Up — 12", "→ 2 rounds"] }, { n: "Cool-Down", it: ["Jog + stretch"] }] },
    sunday: { t: "Recovery · Rest", i: "REST", d: "20-30 min", ic: "😴", rc: true, op: ["Full rest", "Easy walk (20 min)", "Gentle yoga / stretch", "Foam rolling + breathing"], b: [{ n: "", it: ["Choose one recovery option above."] }] },
};

const P2A = {
    monday: { t: "Lower Strength + Power A", i: "HARD", d: "65 min", ic: "🦵", b: [{ n: "Warm-Up — 8 min", it: ["Hip Openers", "World's Greatest Stretch", "Leg Swings", "Glute Bridges"] }, { n: "Main Work", it: ["DB Front Squat — 4×8", "KB Swing (heavy) — 4×12", "DB Walking Lunge — 3×10 each", "Superset: Single-Leg RDL / Slider Ham Curl — 3×10 each", "Box Jump or Broad Jump — 4×5", "Lateral Bound to Stick — 3×6 each"] }, { n: "Core", it: ["Weighted Plank — 3×30s", "Ex. Ball Knee Tuck — 3×12"] }] },
    tuesday: { t: "Upper Hypertrophy A", i: "HARD", d: "70 min", ic: "💪", b: [{ n: "Warm-Up — 8 min", it: ["Hip Openers", "Thoracic Rotations", "Arm Circles", "Band Pull-Aparts"] }, { n: "Main Work", it: ["DB Bench Press — 5×10 (3s negative last 2 sets)", "DB Bent-Over Row — 5×10", "Superset: Incline DB Press / Chest-Supported Row — 4×12", "Giant Set: DB Shoulder Press / Lat Raise / Rear Delt Flye — 3×10-12", "Superset: DB Curl / Tricep Dip — 4×12", "Band Pull-Apart — 3×20"] }, { n: "Metabolic Finisher — 8 min", it: ["30s Jump Rope / 30s Slider Push-Up / 30s KB Swing / 30s Rest — 4 rounds"] }, { n: "Core", it: ["Ex. Ball Rollout — 10", "Lying Leg Raise — 12", "Side Plank — 30s each", "→ 2 rounds"] }] },
    wednesday: { t: "Skill Conditioning A + Core", i: "MODERATE", d: "55 min", ic: "🔥", b: [{ n: "Warm-Up — 8 min", it: ["Ladder: Ali Shuffle", "Ladder: Icky Shuffle"] }, { n: "Circuit — 45s/25s, 70-75% effort", it: ["Block 1 (×3): Lateral Shuffle w/ Band → Carioca → Slider Push-Up → BW Squat Jump", "Block 2 (×3): KB Swing → Push-Up Variation → DB Thruster → Slider Mt. Climber"] }, { n: "Core — 12 min", it: ["V-Ups — 12", "Russian Twist — 20", "Plank Drag (DB) — 8 each", "Bicycle Crunch — 20", "Hollow Body — 30s", "Side Plank Dips — 10 each", "→ 2 rounds"] }] },
    thursday: { t: "Footwork + Agility A", i: "EASY-MOD", d: "35 min", ic: "👟", b: [{ n: "Ladder — game speed", it: ["Ali Shuffle — 3 rounds", "Crossover — 3 rounds", "In-Out-In — 3 rounds", "Lateral Icky — 3 rounds"] }, { n: "Reactive Agility", it: ["T-Drill — 3 reps", "5-10-5 Shuttle at 80% — 4 reps", "Lateral Bound to Sprint — 3×4 each", "Backpedal to Cut and Sprint — 4×20 yds"] }, { n: "Mobility — 10 min", it: ["90/90 Hips", "Pigeon", "Couch Stretch", "Thoracic Rotation", "Banded Shoulder Distraction"] }] },
    friday: { t: "Upper Volume A · Shoulders + Arms", i: "HARD", d: "70 min", ic: "💪", b: [{ n: "Warm-Up — 8 min", it: ["Hip Openers", "Thoracic Rotations", "Arm Circles", "Band Pull-Aparts"] }, { n: "Main Work", it: ["DB Incline Press — 4×10 (3s negative)", "Single-Arm DB Row — 4×10 each", "Superset: Arnold Press / Face Pull — 4×12", "Superset: Chest Flye / Reverse Flye — 3×12", "Superset: Hammer Curl / Diamond Push-Up — 4×12", "Lateral Raise Drop Set — 3 sets (12 heavy + 8 lighter)"] }, { n: "Metabolic Finisher — 8 min", it: ["30s Burpee / 30s DB Snatch / 30s Jump Rope / 30s Rest — 4 rounds"] }, { n: "Core", it: ["Pallof Press — 3×8 each", "Dead Bug w/ Weight — 3×10 each", "Plank Shoulder Tap — 2×12 each"] }] },
    saturday: { t: "Track: Power + Speed A", i: "HARD", d: "60 min", ic: "🏟️", eq: "Jump rope, sliders, weighted vest (wks 9+)", b: [{ n: "Warm-Up — 10 min", it: ["Easy Jog", "Hip Openers", "Leg Swings", "A-Skips", "B-Skips", "High Knees"] }, { n: "Agility — 15 min", it: ["Ladder Drills (full speed)", "5-10-5 Shuttle — 6 reps", "T-Drill — 4 reps", "Reactive Direction Changes"] }, { n: "Power + Speed — 20 min", it: ["Broad Jump — 5 reps", "100m Sprint at 85-90% — 3 reps (full walk-back)", "200m Repeat at 80% — 3 reps (walk back)", "Weighted Vest Sprint 30 yds — 4 reps (wks 9+)"] }, { n: "Core — 10 min", it: ["Sprinter Sit-Ups — 12 each", "Plank Walkout — 8", "Mountain Climber — 20", "V-Up — 12", "Superman Hold — 30s", "→ 2 rounds"] }, { n: "Cool-Down", it: ["Easy jog + stretch on the grass"] }] },
    sunday: { t: "Recovery · Light Cardio + Stretch", i: "EASY", d: "30 min", ic: "🌿", rc: true, op: ["Light jog (15 min) + deep stretch", "Bike ride (20 min) + stretch", "Walk (20 min) + yoga flow", "Foam rolling + mobility only"], b: [{ n: "Deep Stretch — 15 min", it: ["90/90 Hip — 2 min each", "Pigeon — 90s each", "Seated Forward Fold — 90s", "Thoracic Bridge — 60s each", "Wall Pec Stretch — 60s each", "Figure-4 Stretch — 90s each"] }] },
};

const P2B = {
    monday: { t: "Lower Strength + Power B", i: "HARD", d: "65 min", ic: "🦵", b: [{ n: "Warm-Up — 8 min", it: ["Hip Openers", "World's Greatest Stretch", "Leg Swings", "Glute Bridges"] }, { n: "Main Work", it: ["DB Bulgarian Split Squat — 4×8 each (heavy)", "KB Deadlift (heavy) — 4×8", "Superset: DB Step-Up / Nordic Ham Curl Negative — 3×8 each", "DB Cossack Squat — 3×8 each", "Depth Jump to Sprint — 4×3", "Single-Leg Bound — 3×5 each"] }, { n: "Core", it: ["Dragon Flag Negative — 3×5", "Weighted Side Plank — 3×20s each"] }] },
    tuesday: { t: "Upper Hypertrophy B", i: "HARD", d: "70 min", ic: "💪", b: [{ n: "Warm-Up — 8 min", it: ["Hip Openers", "Thoracic Rotations", "Arm Circles", "Band Pull-Aparts"] }, { n: "Main Work", it: ["DB Squeeze Press — 5×10 (3s negative last 2 sets)", "Meadows Row (DB) — 5×10 each", "Superset: Decline Push-Up / Inverted Row (table) — 4×12", "Giant Set: DB Z-Press / Lateral Raise / Band Pull-Apart — 3×10-12", "Superset: Incline Curl / Overhead Tricep Extension — 4×12", "Rear Delt Flye (slow tempo) — 3×15"] }, { n: "Metabolic Finisher — 8 min", it: ["30s Slider Burpee / 30s KB Swing / 30s Push-Up / 30s Rest — 4 rounds"] }, { n: "Core", it: ["Lying Leg Raise — 12", "Plank Drag (DB) — 8 each", "Hollow Body — 30s", "→ 2 rounds"] }] },
    wednesday: { t: "Skill Conditioning B + Core", i: "MODERATE", d: "55 min", ic: "🔥", b: [{ n: "Warm-Up — 8 min", it: ["Ladder: Lateral Zig-Zag", "Ladder: Single-Leg Hops"] }, { n: "Circuit — 45s/25s, 70-75% effort", it: ["Block 1 (×3): Jump Rope → Bear Crawl 10 yds → DB Snatch → Lateral Shuffle", "Block 2 (×3): Burpee → Slider Pike → KB Swing → Skater Bounds"] }, { n: "Core — 12 min", it: ["Ex. Ball Rollout — 10", "Pallof Press — 8 each", "Dead Bug — 10 each", "Side Plank Dips — 10 each", "V-Up — 12", "Plank to Push-Up — 8", "→ 2 rounds"] }] },
    thursday: { t: "Footwork + Agility B", i: "EASY-MOD", d: "35 min", ic: "👟", b: [{ n: "Ladder — game speed", it: ["Single-Leg Hops — 3 rounds each", "Lateral Zig-Zag — 3 rounds", "Quick Feet Sprint-Out — 3 rounds", "Backwards Through — 3 rounds"] }, { n: "Reactive Agility", it: ["L-Drill — 4 reps", "Pro Agility at 85% — 4 reps", "Lateral Bound → Cut → Sprint — 3×4 each", "Mirror Drill (shadow cuts) — 3×15s"] }, { n: "Mobility — 10 min", it: ["90/90 Hips", "Thoracic Foam Roll", "Pigeon", "Banded Hip Distraction", "Calf/Achilles Stretch"] }] },
    friday: { t: "Upper Volume B · Chest + Back", i: "HARD", d: "70 min", ic: "💪", b: [{ n: "Warm-Up — 8 min", it: ["Hip Openers", "Thoracic Rotations", "Arm Circles", "Band Pull-Aparts"] }, { n: "Main Work", it: ["DB Floor Press — 4×10 (3s negative)", "DB Bent-Over Row (wide grip) — 4×10", "Superset: DB Shoulder Press / Single-Arm Row — 4×10", "Superset: Push-Up (feet elevated) / Band Face Pull — 3×15", "Superset: Concentration Curl / Tricep Kickback — 4×12", "DB Chest Flye Drop Set — 3 sets (10 heavy + 8 lighter)"] }, { n: "Metabolic Finisher — 8 min", it: ["30s Thruster / 30s Mt. Climber / 30s KB Snatch / 30s Rest — 4 rounds"] }, { n: "Core", it: ["Russian Twist — 20", "Ex. Ball Pike — 8", "Side Plank — 30s each", "→ 2 rounds"] }] },
    saturday: { t: "Track: Power + Speed B", i: "HARD", d: "60 min", ic: "🏟️", eq: "Jump rope, sliders, weighted vest (wks 9+)", b: [{ n: "Warm-Up — 10 min", it: ["Easy Jog", "Hip Openers", "Leg Swings", "A-Skips", "B-Skips"] }, { n: "Agility — 15 min", it: ["Ladder Drills (full speed, B patterns)", "L-Drill — 5 reps", "Pro Agility — 5 reps", "Reactive Cut Drill — 4×15s"] }, { n: "Power + Speed — 20 min", it: ["Standing Triple Jump — 4 reps", "60m Sprint at 90% — 4 reps (full recovery)", "300m at 75% — 2 reps (3 min rest)", "Hill Sprint or Weighted Vest 40 yds — 4 reps (wks 9+)"] }, { n: "Core — 10 min", it: ["Bicycle Crunch — 20", "Plank to Push-Up — 10", "Sprinter Sit-Up — 12 each", "Flutter Kicks — 20 each", "Superman — 30s", "→ 2 rounds"] }, { n: "Cool-Down", it: ["Easy jog + stretch"] }] },
    sunday: { t: "Recovery · Light Cardio + Stretch", i: "EASY", d: "30 min", ic: "🌿", rc: true, op: ["Light jog (15 min) + deep stretch", "Bike ride (20 min) + stretch", "Walk (20 min) + yoga flow", "Foam rolling + mobility only"], b: [{ n: "Deep Stretch — 15 min", it: ["90/90 Hip — 2 min each", "Pigeon — 90s each", "Couch Stretch — 60s each", "Thoracic Bridge — 60s each", "Lat Stretch — 60s each", "Child's Pose — 90s"] }] },
};

const EG = { 
    "Chest Press": ["DB Floor Press", "DB Bench Press", "DB Incline Press", "Incline DB Press", "DB Squeeze Press"], 
    "Row": ["DB Bent-Over Row", "Single-Arm DB Row", "Meadows Row", "Chest-Supported Row", "Renegade Row"], 
    "Shoulder Press": ["DB Shoulder Press", "Arnold Press", "DB Z-Press", "Half-Kneeling DB Shoulder Press"], 
    "Curl": ["DB Curl", "Hammer Curl", "Incline Curl", "Concentration Curl"], 
    "Tricep": ["Overhead Tricep Extension", "Tricep Dip", "Tricep Kickback"], 
    "Squat": ["Goblet Squat", "DB Front Squat", "DB Sumo Squat", "DB Bulgarian Split Squat", "DB Cossack Squat", "Thruster", "DB Thruster"], 
    "Hinge": ["KB Romanian Deadlift", "Single-Leg RDL", "KB Deadlift", "KB Sumo Deadlift"], 
    "KB Swing": ["KB Swing"], 
    "Clean": ["KB Clean and Press", "DB Snatch", "KB Snatch"], 
    "Carry": ["Farmer's Carry", "Suitcase Carry"] 
};
